src/app.py
from flask import Flask, render_template
from src.common.database import Database

__author__ = 'Vedant Sharma'

app = Flask(__name__)
app.config.from_object('src.config')  # Uncomment this in Production
# app.config.from_pyfile('config.py')  # Uncomment this during development and staging


@app.before_first_request
def initialize_database():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.html')


from src.models.users.views import user_blueprint
from src.models.tasks.views import task_blueprint
app.register_blueprint(user_blueprint, url_prefix='/users')
app.register_blueprint(task_blueprint, url_prefix='/tasks')

src/models/tasks/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from src.models.tasks.task import Task
import src.models.tasks.errors as TaskErrors
import datetime

__author__ = 'Vedant Sharma'

task_blueprint = Blueprint('tasks', __name__)


@task_blueprint.route('/new', methods=['POST', 'GET'])
def create_task():
    if request.method == 'POST':
        if request.form['action'] == 'create':
            title = request.form['title']
            description = request.form['description']
            group = request.form['cat']
            timeDue = request.form['due-date']
            timeRemind = request.form['remind-at']
            priority = request.form['priority']

            freq_num = request.form['freq']
            freq_timeframe = request.form['freq-time']
            reminderFreq = freq_num + ' ' + freq_timeframe

            user_id = session['email']
            try:
                if Task.create_task(user_id, title, description, timeDue, priority, timeRemind, reminderFreq, group):
                    return redirect(url_for('users.home'))
            except TaskErrors.TaskError as e:
                error = e
                return render_template('tasks/create_task.html', error=error)

        elif request.form['action'] == 'cancel':
            return redirect(url_for('users.home'))

    # What happens if it's a GET request
    return render_template('tasks/create_task.html')


@task_blueprint.route('/delete/<string:task_id>')
def delete_task(task_id):
    Task.delete_single(task_id)
    return redirect(url_for('users.home'))


@task_blueprint.route('/update/<string:task_id>', methods=['GET', 'POST'])
def update_task(task_id):
    old_task = Task.get_by_task_id(task_id)
    freq, timeframe = old_task['reminderFreq'].split(' ')
    old_task['freq'] = freq
    old_task['timeframe'] = timeframe

    if request.method == 'POST':
        if request.form['action'] == 'update':
            update_query = dict()

            if request.form['description'] != old_task['description']:
                update_query['description'] = request.form['description']
            if datetime.datetime.strptime(request.form['due-date'], '%Y-%m-%dT%H:%M') != old_task['timeDue']:
                update_query['timeDue'] = datetime.datetime.strptime(request.form['due-date'], '%Y-%m-%dT%H:%M')
            if datetime.datetime.strptime(request.form['remind-at'], '%Y-%m-%dT%H:%M') != old_task['timeRemind']:
                update_query['timeRemind'] = datetime.datetime.strptime(request.form['remind-at'], '%Y-%m-%dT%H:%M')
            if request.form['cat'] != old_task['group']:
                update_query['group'] = request.form['cat']
            if request.form['priority'] != old_task['priority']:
                update_query['priority'] = request.form['priority']
            if request.form['freq'] + ' ' + request.form['freq-time'] != old_task['reminderFreq']:
                update_query['reminderFreq'] = request.form['freq'] + ' ' + request.form['freq-time']

            full_update_query = {'$set': update_query}
            Task.edit_task(task_id=task_id, edit_query=full_update_query)

            return redirect(url_for('users.home'))

        elif request.form['action'] == 'cancel':
            return redirect(url_for('users.home'))

    return render_template('tasks/edit_task.html', task=old_task)


@task_blueprint.route('/<string:task_id>')
def load_task(task_id):
    task = Task.get_by_task_id(task_id=task_id)
    return render_template('tasks/task.html', task=task)


@task_blueprint.route('/for_user/<string:user_id>')
def load_tasks_for_user(user_id):
    pass

src/models/users/views.py
from flask import Blueprint, render_template, request, session, url_for, redirect
from src.models.users.user import User
import src.models.users.errors as UserErrors

__author__ = 'Vedant Sharma'

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        identifier = request.form['email']
        password = request.form['password']

        try:

            if User.login(identifier, password):
                if User.get_by_mail(identifier) is not None:
                    user = User.get_by_mail(identifier)

                else:
                    user = User.get_by_unm(identifier)

                if user.isAdmin:
                    return render_template('users/admin.html', name=user.name)
                else:
                    tasks = user.get_tasks()
                    return render_template('users/home.html', name=user.name, tasks=tasks)

        except UserErrors.UserError as e:
            error = e
            return render_template('users/login.html', error=error)

    return render_template('users/login.html')


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():

    if request.method == 'POST':

        if request.form["submit"] == "login":
            return render_template("users/login.html")

        name = request.form['name']
        email = request.form['email']
        password = request.form['password']
        username = request.form['username']

        try:
            if User.register(name, email, password, username):
                session['email'] = email
                return render_template('users/home.html', name=name)

        except UserErrors.UserError as e:
            error = e
            return render_template('users/register.html', error=error)

    return render_template('users/register.html')


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


# @user_blueprint.route('/tasks')
# def get_tasks():
#     user = User.get_by_mail(email=session['email'])
#     tasks = User.get_tasks()
#
#     return redirect(url_for('users.get_tasks'))


@user_blueprint.route('/home')
def home():
    email = session['email']
    user = User.get_by_mail(email)
    tasks = user.get_tasks()
    return render_template('users/home.html', name=user.name, tasks=tasks)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODO</title>

    {% include 'html_dependencies.html' %}

</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/" title="Home">TODO</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <!--<ul class="nav navbar-nav">-->
                <!--<li><a href="/users/login">Login</a></li>-->
                <!--<li><a href="/users/register">Register</a></li>-->
            <!--</ul>-->

            {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('users.home') }}"><span class="glyphicon glyphicon-tasks"></span>  My Dashboard</a></li>
                    <li><a href="{{ url_for('tasks.create_task') }}"><span class="glyphicon glyphicon-pencil"></span>  Create Task</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span>  Log in</a></li>
                    <li><a href="{{ url_for('users.register') }}"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1>TODO</h1>
    <p>Manage your daily tasks efficiently </p>
    <p>We will remember your tasks and deadlines for you, while you focus only on your current work! </p>
    <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Get Started</a></p>
</div>

{% endblock %}

src/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

src/templates/tasks/create_task.html
{% extends "base.html" %}
{% block content %}

<div class="page-header">
    <h1>New Task</h1>
</div>
<div class="form-size">

    <form method="post">

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" required pattern=".*\S+.*" placeholder="Title">
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" id="description" name="description" required pattern=".*\S+.*" placeholder="Description">
        </div>

        <div class="form-group">
            <label for="due-date">Due Date</label>
            <input type="datetime-local" class="form-control" id="due-date" required pattern=".*\S+.*" name="due-date">
        </div>

        <div class="form-group">
            <label for="cat">Category</label>
            <input type="text" class="form-control" id="cat" name="cat" required pattern=".*\S+.*" placeholder="Category">
        </div>

        <div class="form-group">
            <label for="priority">Priority</label>
            <select class="form-control" id="priority" name="priority">
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
            </select>
        </div>

        <div class="form-group">
            <label for="remind-at">Remind At</label>
            <input type="datetime-local" class="form-control" id="remind-at" required pattern=".*\S+.*" name="remind-at">
        </div>

        <div class="form-group">
            <div class="input-group">
                <label for="freq">Reminder Frequency</label>
                <!--<p>After Every</p>-->
                <input type="text" class="form-control" id="freq" name="freq" required pattern=".*\S+.*" placeholder="30" value="30">
                <select class="form-control" id="freq-time" name="freq-time">
                    <option value="min">Minute(s)</option>
                    <option value="hr">Hour(s)</option>
                    <option value="day">Day(s)</option>
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-success" name="action" value="create"><span class="glyphicon glyphicon-plus"></span> Create</button>
        <button type="submit" class="btn btn-danger" name="action" value="cancel" formnovalidate><span class="glyphicon glyphicon-remove"></span> Discard</button>
        <br/>
        <br/>
        {% if error %}
        <div class="alert alert-danger" role="alert">
            <p class="error"><strong>Error:</strong> {{ error }}</p>
        </div>
        {% endif %}

    </form>
</div>

{% endblock %}

src/templates/tasks/edit_task.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Task</h1>
    </div>
    <div class="form-size">
        <form method="post">

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" required pattern=".*\S+.*" title="This field is required" placeholder="{{ task.title }}" disabled>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" id="description" name="description" required pattern=".*\S+.*" title="This field is required" value="{{ task.description }}">
        </div>

        <div class="form-group">
            <label for="due-date">Due Date</label>
            <input type="datetime-local" class="form-control" id="due-date" name="due-date" required pattern=".*\S+.*" title="This field is required" value="{{ task.timeDue.strftime('%Y-%m-%dT%H:%M') }}">
        </div>

        <div class="form-group">
            <label for="cat">Category</label>
            <input type="text" class="form-control" id="cat" name="cat" required pattern=".*\S+.*" title="This field is required" value="{{ task.group }}">
        </div>

        <div class="form-group">
            <label for="priority">Priority</label>
            <select class="form-control" id="priority" name="priority">
                {% if task.priority == "low" %}
                <option value="low" selected="selected">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                {% elif task.priority == "medium" %}
                <option value="low">Low</option>
                <option value="medium" selected="selected">Medium</option>
                <option value="high">High</option>
                {% else %}
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high" selected="selected">High</option>
                {% endif %}
            </select>
        </div>

        <div class="form-group">
            <label for="remind-at">Remind At</label>
            <input type="datetime-local" class="form-control" id="remind-at" name="remind-at" required pattern=".*\S+.*" title="This field is required" value="{{ task.timeRemind.strftime('%Y-%m-%dT%H:%M') }}">
        </div>

        <div class="form-group">
            <div class="input-group">
                <label for="freq">Reminder Frequency</label>
                <input type="text" class="form-control" id="freq" name="freq" required pattern=".*\S+.*" title="This field is required" value="{{ task.freq }}">
                <select class="form-control" id="freq-time" name="freq-time">
                    {% if task.timeframe == "min" %}
                    <option value="min" selected="selected">Minute(s)</option>
                    <option value="hr">Hour(s)</option>
                    <option value="day">Day(s)</option>
                    {% elif task.timeframe == "hr" %}
                    <option value="min">Minute(s)</option>
                    <option value="hr" selected="selected">Hour(s)</option>
                    <option value="day">Day(s)</option>
                    {% else %}
                    <option value="min">Minute(s)</option>
                    <option value="hr">Hour(s)</option>
                    <option value="day" selected="selected">Day(s)</option>
                    {% endif %}
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-success" name="action" value="update"><span class="glyphicon glyphicon-plus"></span> Update</button>
        <button type="submit" class="btn btn-danger" name="action" value="cancel" formnovalidate><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        </form>
    </div>
{% endblock %}

src/templates/tasks/task.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>{{ task.title }}</h1>
    </div>
    <p>Due on <strong>{{ task.timeDue.strftime('%d-%m-%Y at %I:%M %p') }}</strong></p>
    <p>Description: <strong>{{ task.description }}</strong></p>
    <p>Category: <strong>{{ task.group }}</strong></p>
    <p>Priority: <strong>{{ task.priority }}</strong></p>
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-danger" href="{{ url_for('tasks.delete_task', task_id=task._id) }}" role="button">Delete Task</a>
            <a class="btn btn-warning" href="{{ url_for('tasks.update_task', task_id=task._id) }}" role="button">Edit Task</a>
        </div>
    </div>
{% endblock %}

src/templates/users/admin.html
{% extends "base.html" %}
{% block content %}
<div class="container profile">
    <br/>
    <br/>
    <h1 align="center">Hello {{ name }} !</h1>
    <h2 align="center">Welcome to the Admin Console</h2>
    <h3 align="center"><a href="{{ url_for('users.logout_user') }}"><b>Sign Out</b></a></h3>
</div>
{% endblock %}

src/templates/users/home.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>My Tasks</h1>
    </div>
    <div class="list-group">
    {% for task in tasks %}
        <a href="{{ url_for('tasks.load_task', task_id=task._id) }}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ task.title }}</h4>
            <p class="list-group-item-text">{{ task.description }}</p>
        </a>
    {% endfor %}
    </div>
{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<br/>
<br/>
<div class="form-size">
    <form id="login-form" action="{{ url_for('users.login') }}" method="post">
        <div class="form-group">
            <label for="email">Email or Username</label>
            <input type="text" id="email" class="form-control" name="email", placeholder="Email or Username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" class="form-control" name="password", placeholder="Password">
        </div>

        <button type="submit" class="btn btn-success">Log in</button>
    </form>
    <br/>
    {% if error %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <p class="error"><strong>Error:</strong> {{ error }}</p>
        </div>
    {% endif %}
    <p>Not a TODO user? <a href="{{ url_for('users.register') }}">Register</a> to get started!</p>
</div>

<br/>

{% endblock %}

src/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container profile">
    <br/>
    <br/>
    <h1 align="center">Hello {{ name }} !</h1>
    <h3 align="center"><a href="{{ url_for('users.logout_user') }}"><b>Sign Out</b></a></h3>
</div>
{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
<br/>
<br/>
<div class="form-size">
    <form id="login-form" action="{{ url_for('users.register') }}" method="post">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" id="name" class="form-control" name="name", placeholder="Name">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" id="email" class="form-control" name="email", placeholder="Email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" id="password" class="form-control" name="password", placeholder="Password">
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" class="form-control" name="username", placeholder="Username">
        </div>

        <button type="submit" class="btn btn-success" name="submit" value="register">Sign Up</button>
        <br/>
        <br/>
        {% if error %}
        <div class="alert alert-danger" role="alert">
            <p class="error"><strong>Error:</strong> {{ error }}</p>
        </div>
        {% endif %}
    </form>
    <p>Already a User? <a href="{{ url_for('users.login') }}">Sign in</a></p>
</div>
{% endblock %}